[package]
authors = ["Mathew Robinson <chasinglogic@gmail.com>"]
name = "licensure"
version = "0.1.2"
keywords = ["licensing", "cli", "tool", "license"]
license = "GPL-3.0"
readme = "README.md"
description = "A software license management tool"
repository = "https://github.com/chasinglogic/licensure"
homepage = "https://github.com/chasinglogic/licensure"

[badges]
travis-ci = { repository = "chasinglogic/licensure", branch = "master" }

[dependencies]
chrono = "0.4.2"
clap = "2.31.2"
regex = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
