[package]
authors = ["Mathew Robinson <chasinglogic@gmail.com>"]
name = "licensure"
version = "0.2.1"
keywords = ["licensing", "cli", "tool", "license"]
license = "GPL-3.0"
readme = "README.md"
description = "A software license management tool"
repository = "https://github.com/chasinglogic/licensure"
homepage = "https://github.com/chasinglogic/licensure"
edition = "2018"

[badges]
travis-ci = { repository = "chasinglogic/licensure", branch = "master" }

[dependencies]
chrono = "0.4.2"
clap = "2.31.2"
regex = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.21"
log = "0.4.8"
simplelog = "0.11.0"
reqwest = { version = "0.11.10", features = ["json"] }
textwrap = "0.14.2"
futures = "0.3"
